### ISSUE TITLE
Issues with published package

### ISSUE THREAD

**Issue by WillsterJohnson** [rodydavis/postcss-color-hct#4]
The project is using typescript as it's source code, but no `.d.ts` files are present when installing from NPM, why is this?

Also, a lot of things *are* there that shouldn't be. Maybe the `.npmignore` file needs an update;
```sh
# NPM will refuse to ignore files such as readme or license,
# so even if you add them here (as they are now)
# they won't actually be ignored.
# 
# The only stuff end users need is the contents of dist and
# any NPM required files
!/dist/
```

**Comment by rodydavis** [comment]
Thank you! Will update

**Comment by rodydavis** [comment]
Waiting on https://github.com/postcss/postcss/pull/1773 to land for postcss, but could add a declaration file for the cjs

**Comment by rodydavis** [comment]
updated: 0.3.0
